### ISSUE TITLE
Support for Laravel 10 / PHP 8

### ISSUE THREAD

**Issue by newtovaux** [BRACKETS-by-TRIAD/craftable#423] opened 2023-04-13 07:04 UTC
When attempting to do a manual install in an existing but fresh Laravel 10 / PHP 8 project, some of the dependencies are showing incompatibilities:

  Problem 1
    - brackets/craftable[v1.0.1, ..., v1.0.5] require brackets/translatable ^1.0 -> satisfiable by brackets/translatable[v1.0.0, v1.0.1, v1.0.2, v1.1.0].
    - brackets/craftable[v2.0.0, ..., v2.0.2] require brackets/admin-listing ^2.0 -> satisfiable by brackets/admin-listing[v2.0.0, ..., v2.1.1].
    - brackets/craftable[v3.0.3, ..., v3.1.1] require brackets/admin-ui ^3.1 -> satisfiable by brackets/admin-ui[v3.1.0, v3.1.1].
    - brackets/craftable[v3.0.0, ..., v3.0.2] require brackets/admin-ui ^3.0 -> satisfiable by brackets/admin-ui[v3.0.0, v3.0.1, v3.1.0, v3.1.1].
    - brackets/craftable v1.0.0 requires brackets/admin-listing @dev -> satisfiable by brackets/admin-listing[v1.0.0, v1.0.1, v2.0.0, ..., v2.1.1, v3.0.0, ..., 3.4.0].
    - brackets/admin-listing[v1.0.0, ..., v1.0.1, v2.0.0] require illuminate/support 5.5.* -> found illuminate/support[v5.5.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - brackets/translatable v1.0.0 requires laravel/framework 5.5.* -> found laravel/framework[v5.5.0, ..., v5.5.50] but it conflicts with your root composer.json require (^10.0).
    - brackets/translatable v1.0.1 requires laravel/framework 5.5.*|5.6.* -> found laravel/framework[v5.5.0, ..., v5.6.40] but it conflicts with your root composer.json require (^10.0).
    - brackets/translatable v1.0.2 requires laravel/framework 5.5.*|5.6.*|5.7.* -> found laravel/framework[v5.5.0, ..., v5.7.29] but it conflicts with your root composer.json require (^10.0).
    - brackets/admin-listing v2.0.1 requires illuminate/support 5.5.*|5.6.* -> found illuminate/support[v5.5.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - brackets/translatable v1.1.0 requires php ^7.1 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-listing v2.1.1 requires php ^7.1 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-ui v3.1.1 requires php ^7.1 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/craftable[v4.0.0, ..., v4.0.1] require php ^7.1 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-listing[v2.0.2, ..., v2.1.0] require illuminate/support 5.5.*|5.6.*|5.7.* -> found illuminate/support[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - brackets/admin-ui[v3.0.0, ..., v3.1.0] require illuminate/support 5.5.*|5.6.*|5.7.* -> found illuminate/support[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - brackets/craftable[v5.0.0, ..., v5.0.2] require php ^7.2 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-listing v3.0.0 require php ^7.2 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/craftable v5.1.0 requires php ^7.2.5 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-listing v3.1.0 requires php ^7.2.5 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/craftable 6.0.0 requires php ^7.4.0 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/craftable 7.0.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - brackets/admin-listing 3.3.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - brackets/admin-listing 3.2.0 requires php ^7.2.5|^7.3.0 -> your php version (8.2.1) does not satisfy that requirement.
    - brackets/admin-listing 3.4.0 requires illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.
    - brackets/craftable[8.0.0, ..., v8.0.1] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires brackets/craftable * -> satisfiable by brackets/craftable[v1.0.0, ..., v1.0.5, v2.0.0, v2.0.1, v2.0.2, v3.0.0, ..., v3.1.1, v4.0.0, v4.0.1, v5.0.0, v5.0.1, v5.0.2, v5.1.0, 6.0.0, 7.0.0, 8.0.0, v8.0.1].

**Comment by verybigelephants** [comment] 2023-06-20 13:15
Is there perhaps any timeline estimate on when is the non-pro version going to be supported by laravel 10? :)

**Comment by francosalcedo** [comment] 2023-08-23 15:26
Any new :(?

**Comment by palypster** [comment] 2023-10-30 09:40
All the PRs were merged, we are about to make a release after some final testing:
https://github.com/BRACKETS-by-TRIAD/craftable/pull/426

**Comment by francosalcedo** [comment] 2023-10-30 14:42
> All the PRs were merged, we are about to make a release after some final testing: #426

Very thanks man!

**Closed** 2023-10-30 14:56 UTC

**Comment by verybigelephants** [comment] 2023-11-12 17:49
i think this will need more work than just that

for example, when you try to use native larael breeze user auth scaffolding there's a conflict, as it expects package.json  to have `"type": "module"`, which is incompatible with craftable admin builder

**Comment by erikgreasy** [comment] 2023-11-13 10:43
@verybigelephants we will have a look at that

**Comment by erikgreasy** [comment] 2023-11-13 11:49
I was able to reproduce the problem with clean Laravel installation with Breeze and Craftable. The main issue seems to be with `postcss.config.js` file, which uses the `export` syntax which is not working without `"type": "module"`, causing `npm run dev` to fail. Anyway, I managed to fix the issue by renaming `postcss.config.js` => `postcss.config.mjs`. 

Can you try this and see if this helps resolve the issue in your project @verybigelephants ?

**Comment by verybigelephants** [comment] 2023-11-13 12:48
i have solved it by renaming `postcss.config.js` to `postcss.config.cjs` and replaced the syntax inside the file to this format

`module.exports = ({ env }) => ({ plugins: [ require('tailwindcss')(), require('autoprefixer')() ] })` 

as mentioned [here](https://github.com/BuilderIO/qwik/issues/836#issuecomment-1518896812)
