### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by aimensasi** [BRACKETS-by-TRIAD/craftable#14] opened 2018-02-02 03:57 UTC
After running the below command I get an error

The Command 
```
composer global require "brackets/craftable-installer"
```

The Error 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brackets/craftable-installer v1.0.6 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.5 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.4 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.3 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.2 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.1 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.0 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for brackets/craftable-installer ^1.0 -> satisfiable by brackets/craftable-installer[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].
```

**Comment by palypster** [comment] 2018-02-02 09:26
That's really weird, try this and let me know:
`
composer global remove "laravel/installer"
composer global remove "brackets/craftable-installer"
composer global require "laravel/installer"
composer global require "brackets/craftable-installer"
`

**Comment by aimensasi** [comment] 2018-02-05 11:04
Still the same problem 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brackets/craftable-installer v1.0.6 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.5 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.4 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.3 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.2 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.1 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.0 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for brackets/craftable-installer ^1.0 -> satisfiable by brackets/craftable-installer[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].
```

**Comment by tstechnik** [comment] 2018-02-08 14:19
I have the Same problem

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brackets/craftable-installer v1.0.6 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.5 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.4 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.3 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.2 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.1 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.0 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for brackets/craftable-installer ^1.0 -> satisfiable by brackets/craftable-installer[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].


Installation failed, reverting ./composer.json to its original content.`

**Comment by palypster** [comment] 2018-02-08 14:31
Guyz, can you both send your `laravel` version?
```
laravel --version
```

**Comment by tstechnik** [comment] 2018-02-08 14:32
Laravel 5.5

**Comment by tstechnik** [comment] 2018-02-08 14:33
I have install a clean Laravel 5.5 after this add Craftable to my existing project. When i go this way, become this error:
```
In Connection.php line 664:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'json not null, `custom_properties`  
   json not null, `order_column` int unsigned nu' at line 1 (SQL: create tabl  
  e `media` (`id` int unsigned not null auto_increment primary key, `model_id  
  ` int unsigned not null, `model_type` varchar(191) not null, `collection_na  
  me` varchar(191) not null, `name` varchar(191) not null, `file_name` varcha  
  r(191) not null, `mime_type` varchar(191) null, `disk` varchar(191) not nul  
  l, `size` int unsigned not null, `manipulations` json not null, `custom_pro  
  perties` json not null, `order_column` int unsigned null, `created_at` time  
  stamp null, `updated_at` timestamp null) default character set utf8mb4 coll  
  ate utf8mb4_unicode_ci)                                                      
                                                                               

In PDOConnection.php line 79:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'json not null, `custom_properties`  
   json not null, `order_column` int unsigned nu' at line 1                    
                                                                               

In PDOConnection.php line 77:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'json not null, `custom_properties`  
   json not null, `order_column` int unsigned nu' at line 1   
```

**Comment by palypster** [comment] 2018-02-08 14:59
I think we have several problems here:
1. laravel installer was updated and this was causing error - we have release new fix for this, so you can try again `composer global require "brackets/craftable-installer"`
1. but this alone won't help becuase also Laravel was updated just yesterday :) to 5.6 and as long as `laravel new` installs by default latest version this breaks our craftable installer, so we need to update it. We'll let you know.

**Comment by aimensasi** [comment] 2018-02-09 02:35
`Laravel Installer 2.0.1`

**Comment by aimensasi** [comment] 2018-02-09 02:38
```
Changed current directory to /Users/AIMEN.S.A/.composer
Using version ^1.0 for brackets/craftable-installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brackets/craftable-installer v1.0.7 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.6 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.5 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.4 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.3 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.2 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.1 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - brackets/craftable-installer v1.0.0 requires laravel/installer ~1.4 -> satisfiable by laravel/installer[v1.4.0, v1.4.1, v1.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for brackets/craftable-installer ^1.0 -> satisfiable by brackets/craftable-installer[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].

```
Still got the same problem. Should we expect a fix for this soon.

**Comment by palypster** [comment] 2018-02-10 08:46
@aimensasi can you post the full content of your global `composer.json` file (`/Users/AIMEN.S.A/.composer/composer.json`)?

**Comment by palypster** [comment] 2018-02-10 14:44
The second issue (incorrectly installing Laravel 5.6) was fixed in this update: https://github.com/BRACKETS-by-TRIAD/craftable-installer/releases/tag/v1.0.8

@aimensasi but I guess that won't help your problem. We really need to find out why your dependencies cannot be resolved - there is something really weird we are not able to reproduce. It is worth a try to completely remove your global composer.json and start over.

**Closed** 2018-02-12 16:03 UTC

**Comment by aimensasi** [comment] 2018-02-12 23:50
My composer.json has only these two lines

```
{
    "require": {
        "laravel/valet": "^2.0",
        "laravel/installer": "^2.0"
    }
}

```

**Comment by palypster** [comment] 2018-02-13 11:49
Sorry @aimensasi, we are not able to reproduce it.

I have removed everything from my global composer.json and I run composer update. It has removed everything. Then I have copied exactly your composer.json file and run composer update again and I got installed all the dependencies you have. After that I run `composer global require "brackets/craftable-installer"` and everything run smoothly without any error.

I'm out of ideas... it's really weird.

**Comment by Pablo-hub44** [comment] 2022-04-18 04:11
same problem in laravel 9 :,v

**Comment by palypster** [comment] 2022-04-19 09:22
Hi, if your global composer has some conflict while installing craftable installer, then you have to either resolve it (remove the conflicting package or align it with craftable) or do not use craftable installer and install craftable manually.
