### ISSUE TITLE
User tooltip timestamp is counting live

### ISSUE THREAD

**Issue by palypster** [BRACKETS-by-TRIAD/craftable#138] opened 2019-09-14 12:07 UTC
When I generate the CRUD with:
```
$table->unsignedInteger('created_by_admin_user_id');
$table->foreign('created_by_admin_user_id')->references('id')->on('admin_users')->onDelete('cascade');
```
and seeds some data in, then I see tooltipin the listing, but instead of seeing date and time of creation of the Post, I see the current timestamp and - wait for it - it's counting :D

**Comment by RichardDominik** [comment] 2019-09-18 13:03
The issue is now resolved in new release https://github.com/BRACKETS-by-TRIAD/admin-generator/releases/tag/v5.0.1

**Closed** 2019-09-18 13:04 UTC
