### ISSUE TITLE
Change password not working

### ISSUE THREAD

**Issue by nucreativa** [BRACKETS-by-TRIAD/craftable#68] opened 2018-12-18 05:52 UTC
Hi Team, change password (/admin/password) not working as expected, based on what i saw on demo site. 

It says "The password confirmation does not match." for any scenario 
1. When the passwords less than 7 chars
2. When the passwords more than 7 chars and using 1 number
3. When the confirmation password doesn't match

**Comment by rapgithub** [comment] 2019-01-08 02:12
same problem here cannot change password :( in admin does not match ever !

**Comment by rapgithub** [comment] 2019-01-08 10:21
password cannot be changed!!! always says this error! after login in the administration!! :( 

<img width="1025" alt="screenshot 2019-01-08 at 11 20 49" src="https://user-images.githubusercontent.com/11996194/50824675-84950b00-1337-11e9-8867-9c41d5b0f1db.png">

**Comment by rapgithub** [comment] 2019-01-09 08:31
thank I will try I was getting so frustrated not being able to change the password of the admin!!! thanks a lot I will try and let you know if error comes!

**Comment by rapgithub** [comment] 2019-01-09 08:47
it still the same error!

1) first I checked that I have the admin generator installed 
composer require --dev brackets/admin-generator

2) I run this on the dir I have all my file installed 
php artisan admin:generate:user:profile -f

and after that I run : npm install && npm run dev

and entered to the login screen deleted cache and showing the same issue, the password cannot be changed because it does not match or even if I add a new user I cannot because of the same problem...

:( any other thing I need to run for this to work ?
thanks


![Uploading Screenshot 2019-01-09 at 09.44.25.png…]()

**Comment by dejwCake** [comment] 2019-01-09 08:51
Please can you provide your composer.lock file? And also generated file resources/views/admin/profile/edit-password.blade.php. Thank you.

**Comment by rapgithub** [comment] 2019-01-09 09:07
here I include them:

[composerlock and editpassword.blade.zip](https://github.com/BRACKETS-by-TRIAD/craftable/files/2740067/composerlock.and.editpassword.blade.zip)

take a look thanks

**Comment by rapgithub** [comment] 2019-01-09 09:17
another interesting thing about all this Craftable installation it is that if at the login screen I want to retrieve my password because I supposed to forget it I get this error on the screen:

<img width="499" alt="screenshot 2019-01-09 at 10 15 52" src="https://user-images.githubusercontent.com/11996194/50889173-99d16e80-13f7-11e9-94ec-095956f00f02.png">

<img width="866" alt="screenshot 2019-01-09 at 10 15 57" src="https://user-images.githubusercontent.com/11996194/50889181-a0f87c80-13f7-11e9-9e3e-a29a3a348cc4.png">

I do not know if this also has to do with the previous problem but in my case I cannot use forget password too... 

:(

**Comment by dejwCake** [comment] 2019-01-09 09:23
This problem is that you did not correctly setup mail settings. It’s a laravel issue, firstly you have to setup your mail provider to get email to reset password. Try: https://laravel.com/docs/5.7/mail#mail-and-local-development

**Comment by dejwCake** [comment] 2019-01-09 12:38
We have found the problem, will be fixed soon. The problem is still in admin-generator.

**Comment by rapgithub** [comment] 2019-01-09 13:16
thanks I wait for your update and reply thanks a lot for taking care about this issue!
I wait...

**Comment by dejwCake** [comment] 2019-01-09 16:12
So this issue should be fixed in admin-generator v2.0.10.

**Comment by rapgithub** [comment] 2019-01-09 17:19
should I look in this link:
https://github.com/BRACKETS-by-TRIAD/admin-generator?

It is now fixed? I see two hours ago was the latest commit but it does not mention this issue ....
thanks

**Comment by rapgithub** [comment] 2019-01-11 22:03
any news about the release? I checked and still 2.0... thanks

**Comment by palypster** [comment] 2019-01-13 21:48
I ask for a little more patience, Craftable 3.0 will be out soon (definitely during upcoming week).

**Comment by palypster** [comment] 2019-01-31 12:38
Hey @rapgithub, we have great news, Craftable v3 is out. This should be fixed now. If not, don't hesitate to file a new issue. Thank you.

**Closed by palypster** 2019-01-31 12:38 UTC
