### ISSUE TITLE
Export login route from vendor to application

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#187] opened 2020-01-27 13:48 UTC
Hello,

How can we export the login and register routes out of vendor to our app?

Actually, is there a way to download a version where everything is out of the vendor (so nothing is a package) but rather as a complete separate app ?

Also is it normal that the register action is not working? Don't you guys have a default register page?

**Comment by palypster** [comment] 2020-01-28 22:14
No, it's not possible. But you can override using standard Laravel techniques:
- https://laravel.com/docs/6.x/container
- https://laravel.com/docs/6.x/packages#views -> Overriding Package Views

About the register action - it was designed like this. The purpose of a Craftable is mainly to provide a way building admin interfaces. In such projects, it really doesn't make sense to have self-registration feature (in 99% cases).

But it's perfectly possible to create your own controllers within your App namespace and re-use the AdminUser model and create registration feature yourself, it's perfectly doable.

Sorry I must close this, because there is not much we can do. But feel free to ask more, if I can help, I'll help!! ;-)

**Closed by palypster** 2020-01-28 22:14 UTC

**Comment by elshobokshy** [comment] 2020-02-02 12:22
@palypster okay so I'm posting this here in case someone's looking for the same thing. This is what I did to get the application out of the vendor package. This is a 3 step process. 

1) Remove the packages from composer

```
    "require": {
        ...
        "brackets/craftable": "^5.0", <==== remove this line 
        ...
    },
    "require-dev": {
        ...
        "brackets/admin-generator": "^5.0", <==== remove this line 
        ...
    }
```

2) Move the whole brackets folder to a `packages/` folder (create it if it doesn't exist) and then add these packages to autoload : 

```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Brackets\\AdminAuth\\": "packages/brackets/admin-auth/src",
            "Brackets\\AdminGenerator\\": "packages/brackets/admin-generator/src",
            "Brackets\\AdminListing\\": "packages/brackets/admin-listing/src",
            "Brackets\\AdminTranslations\\": "packages/brackets/admin-translations/src",
            "Brackets\\AdminUI\\": "packages/brackets/admin-ui/src",
            "Brackets\\AdvancedLogger\\": "packages/brackets/advanced-logger/src",
            "Brackets\\Craftable\\": "packages/brackets/craftable/src",
            "Brackets\\Media\\": "packages/brackets/media/src",
            "Brackets\\Translatable\\": "packages/brackets/translatable/src"
        },
        ...
    },
```

3) Run `composer dumpauto`

This is probably not a good idea if you want the next updates of the package. But in my case, the current version is more than enough.

**Comment by jomko** [comment] 2020-07-07 16:12
Just use Laravel Overriding Package Views technique. For login view we need to copy `vendor/brackets/admin-auth/resources/views/admin/auth/login.blade.php` to `resources/views/vendor/brackets/admin-auth/admin/auth/login.blade.php`
![login](https://user-images.githubusercontent.com/2182831/86809921-10027000-c085-11ea-85f1-d72231be27b0.png)

**Comment by chozzz** [comment] 2020-08-13 19:51
I am posting here if you want to follow @elshobokshy  solution, in which you want to get it out from vendor to app.

I encountered the following error while reinstalling my app with Craftable v5.1;
```
PHP Fatal error:  Trait 'Spatie\Permission\Traits\HasRoles'
```

And here's what I improved from @elshobokshy solution.

1. Add these to packages autoload:
```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            
            "Spatie\\DbDumper\\": "packages/spatie/db-dumper/src",
            "Spatie\\Image\\": "packages/spatie/image/src",
            "Spatie\\ImageOptimizer\\": "packages/spatie/image-optimizer/src",
            "Spatie\\Backup\\": "packages/spatie/laravel-backup/src",
            "Spatie\\MediaLibrary\\": "packages/spatie/laravel-medialibrary/src",
            "Spatie\\Permission\\": "packages/spatie/laravel-permission/src",
            "Spatie\\Translatable\\": "packages/spatie/laravel-translatable/src",
            "Spatie\\PdfToImage\\": "packages/spatie/pdf-to-image/src",
            "Spatie\\TemporaryDirectory\\": "packages/spatie/temporary-directory/src",
```

2. Add these to `config/app.php` - `Package Service Providers`
```
        Spatie\Backup\BackupServiceProvider::class,
        Spatie\MediaLibrary\MediaLibraryServiceProvider::class,
        Spatie\Permission\PermissionServiceProvider::class,
        Spatie\Translatable\TranslatableServiceProvider::class,
```
